config/routes.rb
Rails.application.routes.draw do
  resources :students
  root 'students#index'
  get '/first_ten'     => 'students#first_ten'
  get '/average_value' => 'students#average_value'
  get '/ip_address'    => 'students#ip_address'

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  has_many :marks
  has_many :students, through: :marks
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :students
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :discipline  
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :marks
  has_many :disciplines, through: :marks
  belongs_to :group
  belongs_to :supervisor
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
  has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.joins(:marks).group("students.id").having("avg(marks.value) > ?", 50).order("avg(marks.value) DESC").paginate(:page => params[:page])
  end

  def first_ten
    @students = Student.joins(:marks).group("students.id").order("avg(marks.value) DESC").limit(10)
    @students.includes(:disciplines)
    render 'students/first_ten'
  end

  def average_value
    set_student
    @students = Student.joins(:marks).joins(:group).where(groups: {semester_number: @student.group.semester_number}).group("students.id").having("avg(marks.value) < ? and avg(marks.value) > ?", params[:from].to_i, params[:to].to_i)
    render 'students/average_value'
  end

  def ip_address
    students = Student.includes(:supervisor, :group).all
    ip_addresses = Student.select("ip_address, count(ip_address)").group("students.ip_address").having("count(ip_address) > ?", 2)
    @students = []
    ip_addresses.each do |i|
      temp = students.select {|bb| bb.ip_address == i.ip_address}
      temp.each do |student|
        @flag = false
        if student.supervisor.characheristic.present?
          @flag = true
          break
        end
      end
      @students.push(temp) if @flag
    end
    @students.flatten!
    render 'students/ip_address'
  end



  # GET /students/1
  # GET /students/1.json

  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :group_id, :birthday, :email, :ip_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test404</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.collection_select(:group_id, Group.all, :id, :title )%>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.surname %></td>
        <td><%= student.group.title %></td>
        <td align = "center"><%= student.group.semester_number %></td>
        <td><%= student.birthday %></td>
        <td><%= student.email %></td>
        <td><%= student.ip_address %></td>
        <td><%= student.marks.average("value").round(2) %></td>
        <td><%= student.supervisor.characheristic %></td>
        <% student.disciplines.order(:title).distinct.each do |disc| %>
          <td><%= disc.marks.where(student_id: student.id).pluck(:value).to_s.gsub(/[\[\]]/, '') %> </td>
        <% end %>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/students/_student_light.html.erb
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.surname %></td>
        <td><%= student.group.title %></td>
        <td align = "center"><%= student.group.semester_number %></td>
        <td><%= student.birthday %></td>
        <td><%= student.email %></td>
        <td><%= student.ip_address %></td>
        <td><%= student.supervisor.characheristic %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/first_ten.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Group</th>
      <th>Semester</th>
      <th>Birthday</th>
      <th>Email</th>
      <th>Ip address</th>
      <th>Average mark</th>
      <th>Characheristic</th>
      <% Discipline.all.each do |discipline| %>
        <th><%= discipline.title %></th>
      <% end %>
      <th colspan="3"></th>

    </tr>
  </thead>
  <%= render 'student' %>

</table>

<br>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Group</th>
      <th>Semester</th>
      <th>Birthday</th>
      <th>Email</th>
      <th>Ip address</th>
      <th>Average mark</th>
      <th>Characheristic</th>
      <% Discipline.all.each do |discipline| %>
        <th><%= discipline.title %></th>
      <% end %>
      <th colspan="3"></th>

    </tr>
  </thead>
  <%= render 'student' %>

</table>
<%= will_paginate @students %>

<br>

<%= link_to 'New Student', new_student_path %>
<%= link_to 'First 10', first_ten_path %>
<%= link_to 'ip address piple', ip_address_path %>

app/views/students/ip_address.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Group</th>
      <th>Semester</th>
      <th>Birthday</th>
      <th>Email</th>
      <th>Ip address</th>
      <th>Characheristic</th>

      <th colspan="3"></th>

    </tr>
  </thead>
  <%= render 'student_light' %>

</table>


<br>

<%= link_to 'Back', students_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @student.surname %>
</p>

<p>
  <strong>Group:</strong>
  <%= @student.group.title %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @student.birthday %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @student.ip_address %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %>
<%= link_to 'Back', students_path %>
<br>
<a>Input parameters for sort users in this semester</a>
<br>
<br>
<input name="To" id="to" placeholder="От" type="text">
<br>
<br>
<input name="from" id="from" placeholder="До" type="text">
<br>
<a href="#" id="button">Press it!</a>

<script type="text/javascript">

$( "#button" ).click(function( event ) {
  event.preventDefault();
  var to    = $("#to").val();
  var from  = $("#from").val();
  var id    = <%= @student.id %>
  var rqst  = $.ajax({
    url: '/average_value',
    type: 'GET',
    data: {to: to, from: from, id: id}
  }).done(function(data){
    console.log(data)
    var sometext = "";
    for (var i = data.students.length - 1; i >= 0; i--) {
              text = "<tr><td>" + data.students[i].name + "</td><td>" + data.students[i].surname + "</td><td>" + data.students[i].birthday + "</td><td>" + data.students[i].email + "</td><td>" + data.students[i].ip_address + "</td><td>" + data.students[i].average + "</td><td>" + data.students[i].semester_number + "</td></tr>";
            sometext += text;
    };
      $("#table").html(sometext);
  });


});
</script>

<table id="table">

</table>